// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mveiamyvneyjvbrnjssd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12ZWlhbXl2bmV5anZicm5qc3NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyNjg4MzksImV4cCI6MjA4Njg0NDgzOX0.VUnj8P3X0VgiJCgPiF2EFGQiRwpThd0mqg_NeyUizuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});